### ISSUE TITLE
Use global typings 

### ISSUE THREAD

**Issue by kifirkin** [vuhrmeister/vscode-meteor#2]
Is there a way not to install typings inside .vscode dir but use global installation instead?

**Comment by vuhrmeister** [comment]
You mean outside your project directory? 
That's not implemented, but should be possible.

For now you can just download the file (https://github.com/vuhrmeister/vscode-meteor/blob/master/meteor-typings/meteor.d.ts) and copy it manually.

Having said that, I just recognized it's a bit outdated. I should add typings for 1.4 and 1.5 🤔

**Comment by kifirkin** [comment]
@vuhrmeister yes, I have already installed meteor typings with `typings install registry:env/meteor --global` and it will be nice if extension will look there first before putting them inside my project dir
